---
- name: Provision | Setup Image
  hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - { role: migibert.terraform, tags: [ 'build' ]}
    - { role: ../../roles/cleanup, tags: [ 'ansible' ], become: yes }
