---

- name: Update first
  apt:
    update_cache: true
    upgrade: safe

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Adding APT Keys
  apt_key:
    url: "{{ item.url }}"
    keyring: "/etc/apt/keyrings/{{ item.file_name }}"
    state: present
  with_items: '{{ apt_keys }}'

- name: Adding APT Repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: '{{ apt_repos }}'

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Install yq
  raw: wget -q $(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4) -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq

- name: Install git secret
  raw: git clone https://github.com/sobolevn/git-secret.git git-secret && cd git-secret && make build && PREFIX="/usr/local" make install

- name: Defaulting to python 3
  raw: update-alternatives --install /usr/bin/python python /usr/bin/python3 1

- name: Install Docker
  raw: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && apt-get -y update && apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin

- name: Install Azure CLI
  raw: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

- name: Install Helm
  raw: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Install Helm Plugins
  raw: "helm plugin install {{ item }}"
  with_items: '{{ helm_plugins }}'

- name: Install Kustomize
  raw: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

- name: Install vCluster CLI
  raw: curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64" && install -c -m 0755 vcluster /usr/local/bin && rm -f vcluster

- name: Install Testkube CLI
  raw: curl -sSLf https://get.testkube.io | sh

- name: Install Helmfile
  raw: |
    wget -q $(curl -s https://api.github.com/repos/helmfile/helmfile/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4)
    tar xfvz helmfile_*.tar.gz
    mv helmfile /usr/local/bin/helmfile && chmod 755 /usr/local/bin/helmfile
