---
- name: Update first
  apt:
    update_cache: true
    upgrade: true

- name: Boostrap python
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: install common packages
  apt: name={{ item }} state=present
  with_items: '{{ common_packages }}'

- name: Boostrap kubectl
  raw: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

- name: GCloud CLI
  raw: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

- name: Install Git-Secret
  raw: echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | tee -a /etc/apt/sources.list && wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | apt-key add - && apt-get update && sudo apt-get install git-secret
