---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Boostrap python
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: install common packages
  apt: name={{ item }} state=present
  with_items: "{{ common_packages }}"
