---

- name: Update first
  apt:
    update_cache: true
    upgrade: safe

- name: Install apt-transport-https
  apt: 
    name: apt-transport-https 
    state: present

- name: Adding APT Keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: '{{ apt_keys }}'

- name: Adding APT Repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: '{{ apt_repos }}'


- name: Install common packages
  apt: 
    name: "{{ common_packages }}"
    state: present

- name: Install git secret
  raw: git clone https://github.com/sobolevn/git-secret.git git-secret && cd git-secret && make build && PREFIX="/usr/local" make install

- name: Bootstrap python
  raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python3 && update-alternatives --install /usr/bin/python python /usr/bin/python3 1)

- name: Install NodeJS
  raw: curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&  apt-get install -y nodejs

- name: Boostrap kubectl
  raw: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

- name: Install Docker
  raw: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && apt-get -y update && apt-get -y install docker-ce docker-ce-cli containerd.io

- name: Install Azure CLI
  raw: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash