---

- name: Prepare | Setup Ansible runtime
  hosts: all
  gather_facts: no

  roles:
    - { role: ../roles/prepare, tags: [ 'ansible' ], become: yes }

- name: Provision | Setup Image
  hosts: all
  vars_files:
    - vars/main.yml

  roles:
    - { role: pixelart.chrome, tags: [ 'build' ]}
    - { role: geerlingguy.docker, tags: [ 'docker' ]}
    - { role: srsp.oracle-java, tags: [ 'build' ]}

- name: CleanUp | Remove package artificats and Ansible
  hosts: all
  gather_facts: no

  roles:
    - { role: ../roles/cleanup, tags: [ 'ansible' ], become: yes }
