
source "docker" "autogenerated_1" {
  changes = ["VOLUME /data", "WORKDIR /data", "ENTRYPOINT /bin/bash"]
  commit  = true
  image   = "buildpack-deps:latest"
  pull    = true
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "ansible" {
    extra_arguments = ["-v"]
    playbook_file   = "ansible/playbook.yml"
    user            = "root"
  }

  post-processor "docker-tag" {
    repository = "toolisticon/base-builder-image"
    tags       = ["latest"]
  }
}
