---
- name: Provision | Setup Image
  hosts: all
  vars:
    - jdk_deb: https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
    # renovate: datasource=ansible-galaxy depName=tecris.ansible-maven
    - maven_version: 3.9.6
  pre_tasks:
    - raw: mkdir -p /etc/ssl/certs/java
    - name: Download JDK
      get_url:
        url="{{ jdk_deb }}"
        dest="/tmp/jdk.deb"
    - name: Install JDK
      apt: deb="/tmp/jdk.deb"
      become: true
    - name: Delete JDK downloiad
      ansible.builtin.file:
        state: absent
        path: /tmp/jdk.deb
    - raw: /usr/bin/printf '\xfe\xed\xfe\xed\x00\x00\x00\x02\x00\x00\x00\x00\xe2\x68\x6e\x45\xfb\x43\xdf\xa4\xd9\x92\xdd\x41\xce\xb6\xb2\x1c\x63\x30\xd7\x92' > /etc/ssl/certs/java/cacerts
  roles:
    - { role: tecris.ansible-maven, maven_major: 3 }
    - { role: ../../roles/cleanup, tags: ['ansible'], become: yes }
