---
- name: Provision | Setup Image
  hosts: all
  vars:
    - java_version: 13
    - java_latest_subversion:
        13: 0.2
    - jdk_file_name: jdk-13.0.2_linux-x64_bin
    - jdk_version_detail: 13.0.2+8
    - jdk_tarball_hash: d4173c853231432d94f001e99d882ca7
  roles:
    - { role: srsp.oracle-java, tags: [ 'build' ]}
    - { role: ../../roles/cleanup, tags: [ 'ansible' ], become: yes }
