---
- name: Provision | Setup Image
  hosts: all
  vars:
    - java_version: 12
  roles:
    - { role: srsp.oracle-java, tags: [ 'build' ]}
    - { role: ../../roles/cleanup, tags: [ 'ansible' ], become: yes }
