---
- name: Provision | Setup Image
  hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - { role: grzegorznowak.nvm_node, tags: [ 'nodejs' ], become: yes }
    - { role: ../../roles/cleanup, tags: [ 'ansible' ], become: yes }
