---
common_packages:
  - "ca-certificates"
  - "curl"
  - "dumb-init"
  - "freetds-dev"
  - "gawk"
  - "gettext"
  - "git"
  - "google-cloud-sdk"
  - "htop"
  - "libxss1"
  - "python3"
  - "python3-pip"
  - "python3-pkg-resources"
  - "python3-setuptools"
  - "lsb-release"
  - "gnupg"
  - "rsync"
  - "chromium"
  - "sudo"
  - "zip"
  - "unzip"
  - "vim"
  - "wget"
  # OCI tooling, see https://danmanners.com/posts/2022-01-buildah-multi-arch/
  - podman
  - buildah
  - qemu-user-static
  # Cloud Tools
  - kubectl
  - jq
  # yq is installed from GitHub
  # DB Clients
  - "postgresql-client"
  # Blocked by https://github.com/dbcli/mssql-cli/pull/505
  #- "mssql-tools"
  #- "mongocli"
  #- "mongodb-database-tools"
snap_packages:
  - jq
  - yq
apt_keys:
  - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  - "https://dl-ssl.google.com/linux/linux_signing_key.pub"
  - "https://packages.microsoft.com/keys/microsoft.asc"
apt_repos:
  - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
  - "deb https://packages.cloud.google.com/apt cloud-sdk main"
  - "deb https://packages.microsoft.com/debian/10/prod buster main"
helm_plugins:
  - "https://github.com/databus23/helm-diff"
  - "https://github.com/jkroepke/helm-secrets"
  - "https://github.com/hypnoglow/helm-s3"
  - "https://github.com/aslafy-z/helm-git"
