---
common_packages:
  - "ca-certificates"
  - "curl"
  - "dumb-init"
  - "gawk"
  - "gettext"
  - "git"
  - "google-cloud-sdk"
  - "htop"
  - "libxss1"
  - "python3-pip"
  - "lsb-release"
  - "gnupg"
  - "rsync"
  - "google-chrome-stable"
  - "sudo"
  - "unzip"
  - "vim"
  - "wget"
  # Cloud Tools
  - kubectl
  # DB Clients
  - "postgresql-client"
  # Blocked by https://github.com/dbcli/mssql-cli/pull/505
  #- "mssql-tools"
  - "mongodb-org-tools"
apt_keys:
  - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  - "https://dl-ssl.google.com/linux/linux_signing_key.pub"
  - "https://packages.microsoft.com/keys/microsoft.asc"
  - "https://www.mongodb.org/static/pgp/server-4.4.asc"
apt_repos:
  - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
  - "deb http://packages.cloud.google.com/apt cloud-sdk main"
  - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
  - "deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main"
  - "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main"
helm_plugins:
  - "https://github.com/databus23/helm-diff"
  - "https://github.com/jkroepke/helm-secrets"
  - "https://github.com/hypnoglow/helm-s3"
  - "https://github.com/aslafy-z/helm-git"
