---
common_packages:
  - "apt-utils"
  - "ca-certificates"
  - "curl"
  - "dumb-init"
  - "freetds-dev"
  - "gawk"
  - "gettext"
  - "git"
  - "htop"
  - "libxss1"
  - "python3"
  - "python3-pip"
  - "python3-pkg-resources"
  - "python3-setuptools"
  - "lsb-release"
  - "gnupg"
  - "rsync"
  - "chromium"
  - "sudo"
  - "zip"
  - "unzip"
  - "vim"
  - "wget"
  # OCI tooling, see https://danmanners.com/posts/2022-01-buildah-multi-arch/
  - podman
  - buildah
  - qemu-user-static
  # Cloud Tools
  - "google-cloud-sdk"
  - kubectl
  - jq
  # yq is installed from GitHub
  # DB Clients
  - "postgresql-client"
  - sqlcmd
  #- "mongocli"
  #- "mongodb-database-tools"
  - "nodejs"
snap_packages:
  - jq
  - yq
apt_keys:
  - url: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
    file_name: k8s.gpg
  - url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    file_name: google.gpg
  - url: "https://packages.microsoft.com/keys/microsoft.asc"
    file_name: microsoft.gpg
  - url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    file_name: nodesource.gpg
apt_repos:
  - "deb [signed-by=/etc/apt/keyrings/k8s.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
  - "deb [signed-by=/etc/apt/keyrings/google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
  - "deb [signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main"
  - "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"
helm_plugins:
  - "https://github.com/databus23/helm-diff"
  - "https://github.com/jkroepke/helm-secrets"
  - "https://github.com/hypnoglow/helm-s3"
  - "https://github.com/aslafy-z/helm-git"
