---
common_packages:
  - "ca-certificates"
  - "curl"
  - "dumb-init"
  - "gawk"
  - "gettext"
  - "git"
  - "google-cloud-sdk"
  - "htop"
  - "libxss1"
  - "python3-pip"
  - "lsb-release"
  - "gnupg"
  - "rsync"
  - "google-chrome-stable"
  - "sudo"
  - "unzip"
  - "vim"
  - "wget"
apt_keys:
  - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  - "https://dl-ssl.google.com/linux/linux_signing_key.pub"
apt_repos:
  - "deb http://packages.cloud.google.com/apt cloud-sdk main"
  - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
