name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Set up packer and dependencies
      run: |
        wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
        unzip packer_1.8.0_linux_amd64.zip
        pip install -r requirements.txt

    - name: Build Base Image
      run: |
        .bin/build-base.sh

    - name: Save Base Image
      run: |
        docker save -o /tmp/base-image.tar toolisticon/base-builder-image

    - name: Upload Base Image
      uses: actions/upload-artifact@v2
      with:
        name: base-image
        path: /tmp/base-image.tar


  build:
    needs: [prepare]
    name: Building ${{ matrix.image }} image(s)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        image: ['ansible','java','nodejs','terraform']

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Set up packer and dependencies
      run: |
        wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
        unzip packer_1.8.0_linux_amd64.zip
        pip install -r requirements.txt

    - name: Download Base Image
      uses: actions/download-artifact@v2
      with:
        name: base-image
        path: /tmp
    -
      name: Load Base Image
      run: |
        docker load --input /tmp/base-image.tar

    - name: Build Image(s)
      run: |
        source ./.bin/_bash.inc
        export image=${{matrix.image}}

        prepareImage "${currentDir}/docker/${image}"
        for entry in ${currentDir}/docker/${image}/*.json;
        do
          buildImage "${currentDir}/docker/${image}" "$entry"
        done

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'develop' || github.ref == 'master'
    steps:
      - uses: actions/checkout@v1

      - name: Set up packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
          unzip packer_1.8.0_linux_amd64.zip

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          email: 'oss@holisticon.de'

      - name: Build and Deploy Release Images
        run: |
          export PATH=$PATH:$(pwd)
          ./.bin/build.sh
          ./.bin/deploy.sh
        if: github.ref == 'master'

      - name: Build and Deploy Snaphot Images
        run: |
          export TIMESTAMP=$(date +%s)
          export PATH=$PATH:$(pwd)
          ./.bin/build.sh $TIMESTAMP
          ./.bin/deploy.sh $TIMESTAMP
        if: github.ref == 'develop'
